# Generated by Django 6.1.1 on 2026-09-13 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PYQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('exam_type', models.CharField(choices=[('mid', 'Mid Semester'), ('end', 'End Semester'), ('internal', 'Internal Assessment'), ('practical', 'Practical Exam')], max_length=20)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyqs', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'PYQ',
                'verbose_name_plural': 'PYQs',
                'ordering': ['-year'],
            },
        ),
    ]
